image: rust:latest

variables:
  TARGETS: x86_64-unknown-linux-gnu arm-unknown-linux-gnueabihf
  TARGET_ARCHNAMES: amd64 armhf
  PKGS: libudev-dev librust-udev-dev librust-libudev-sys-dev librust-libudev-dev

before_script:
  - rustup default stable

release_job:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  release:
    tag_name: 'prerelease-$CI_PIPELINE_IID'
    description: 'automatic build on commit'
    ref: '$CI_COMMIT_SHA'
  artifacts:
    paths:
      - out/*
  script:
    - |
      for TARGET in $TARGET_ARCHNAMES; do
        dpkg --add-architecture "${TARGET}"
      done
    - apt update -y
    - |
      for TARGET in $TARGET_ARCHNAMES; do
        pkglst="crossbuild-essential-$TARGET"
        for PKG in $PKGS; do
          pkglst="$pkglst $PKG:$TARGET"
        done
      done
      apt install -y $pkglst
    - mkdir out
    - SYSROOT="/build/root"
    - export PKG_CONFIG_DIR=
    - export PKG_CONFIG_LIBDIR="${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig"
    - export PKG_CONFIG_SYSROOT_DIR="${SYSROOT}"
    - |
      for TARGET in $TARGETS; do
        echo "Building for $TARGET"
        rustup target add "${TARGET}"
        export PKG_CONFIG_PATH="/usr/lib/${TARGET}/pkgconfig"
        if [[ "${TARGET}" != "x86_64-unknown-linux-gnu" ]]; then
          RUSTFLAGS="-C linker=$(echo $TARGET | sed 's/\-unknown//')-gcc" cargo build --release --target="${TARGET}"
        else
          cargo build --release --target="${TARGET}"
        fi
        mv "target/${TARGET}/release/tary" "out/tary-${TARGET}"
      done
