image: rust:latest

before_script:
  - apt-get update
  - apt-get install -y libudev-dev
  - rustup component add clippy

lint:
  script:
    - cargo clippy --all-targets --all-features --keep-going -- -D warnings

build:
  script:
    - cargo build --verbose

test:
  script:
    - cargo test --verbose
