* Tary
...Is an easy way to organize your life.
Content comes in from sources, get transformed by middleware, and routed to destinations.

** Quick Start
Install `libudev` (i.e. `sudo apt install libudev-dev` on Debian).
#+BEGIN_SRC bash
  git clone https://gitlab.com/theokrueger/tary --depth 1
  cd tary
  cargo install --path .
  tary --create-config
  nano ~/.config/tary/tary.toml
  tary
#+END_SRC

See [[./doc/docs.org][the documentation]] for more information

# ** Usage Patterns
# *** POS System
# Buy a cheap POS printer, and use it as your main destination.
# Content will be printed out on receipt paper, which when completed can be stuck onto a receipt spike (it's very satisfying).

# Recieve new content with an exposed (authenticated) HTTP API from anywhere!


** Adding your own services
The code is very extensible, and the HTTP API source can be easily interacted with by external programs.

If you have a well written, Rust-native source, destination, or middleware you'd like to add: feel free to contribute!
The simpler the better.
