* Tary

** Quick Start
Tary requires [[https://github.com/ollama/ollama][Ollama]] to be installed to work.
#+BEGIN_SRC bash
  # Install tary
  cargo install tary
  # Create the default config
  tary --create-config
  # Edit it to your liking
  nano ~/.config/tary/tary.toml
  # Run ollama
  ollama serve &
  # Run tary
  tary
#+END_SRC

See [[Storing Tokens]], [[Managing Sources]], and [[Managing Destinations]] for info on setting up sources and destinations to your liking.

** Storing Tokens
Tary uses [[https://docs.rs/securestore/latest/securestore/][ssclient]] for key generation and encryption

To create a new key in the default location:
#+BEGIN_SRC bash
  cargo install ssclient
  mkdir -p ~/.local/share/tary/
  cd ~/.local/share/tary/
  ssclient create secrets.json --export-key secrets.key
  # Type your password
#+END_SRC
It is the user's responsibility to keep `secrets.key` safe. It is how Tary opens the secrets database.

** Managing Sources
Adding and enabling or disabling sources:

*** Telegram
1. Create a new bot using [[https://t.me/botfather][@Botfather]] to get a token in the format `123456789:blablabla`

2. Add the token to Tary's secrets store
#+BEGIN_SRC bash
  cd ~/.local/share/tary/
  ssclient set TELOXIDE_TOKEN
  # Type your password
  # Paste the token
#+END_SRC

3. Ensure telegram is enabled in `tary.toml`
#+BEGIN_SRC toml
  # ~/.config/tary/tary.toml
  [sources.telegram]
  enabled = true
#+END_SRC


** Managing destinations
Adding and enabling or disabling destinations:

*** POS Printer (Receipt printer)
1. Get the PID and VID of your POS printer using `lsusb`
#+BEGIN_SRC
  $ lsusb
  ...
  Bus 001 Device 018: ID 04b8:0e15 Seiko Epson Corp. TM-T20II
  ...
#+END_SRC

2. Add a `udev` rule to allow user access to the printer
#+BEGIN_SRC udev
  # /etc/udev/rules.d/92-escpos.rules
  SUBSYSTEM=="usb", ATTR{idVendor}=="04b8", ATTR{idProduct}=="0e15", MODE="0666"
#+END_SRC

Reload udev by running ~udevadm control --reload-rules && udevadm trigger~ as root

3. Ensure the printer is enabled in `tary.toml`
#+BEGIN_SRC toml
  # ~/.config/tary/tary.toml
  [destinations.pos_printer]
  enabled = true
  connection = "USB"
  usb_vid = 0x04b8
  usb_pid = 0x0e15
#+END_SRC
